//! Golden-file parity tests — validates Rust engine output matches Python engine.
//!
//! Fixtures generated by engine/generate_fixtures.py from the Python PromptCompiler.
//! Any mismatch here means the Rust engine diverges from the Python reference.

use std::path::PathBuf;

use serde::Deserialize;

// Import the engine module from the daemon crate
// Note: golden parity tests are integration tests that test the public API

#[derive(Debug, Deserialize)]
struct Fixture {
    name: String,
    input: String,
    expected: String,
}

fn load_fixtures() -> Vec<Fixture> {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("golden.json");
    let contents = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("Failed to read {}: {}", path.display(), e));
    serde_json::from_str(&contents)
        .unwrap_or_else(|e| panic!("Failed to parse {}: {}", path.display(), e))
}

/// Test that doesn't require spell correction parity (spell correction not yet in Rust).
/// These fixtures test the core pipeline: symbolic mapping, stop-words, structural, normalization.
const SPELL_INDEPENDENT_FIXTURES: &[&str] = &[
    // Filler removal
    "filler_iwantyouto",
    // Symbolic mapping
    "sym_cot",
    "sym_json",
    "sym_expert",
    "sym_role",
    "sym_function",
    "sym_compare",
    "sym_table",
    "sym_strict",
    "sym_brief",
    "sym_chain",
    // Negation-aware
    "neg_donot_act",
    "neg_never_pretend",
    "neg_not_expert",
    // Stop-word stripping
    "stop_basic",
    "stop_protected",
    // Structural
    "struct_list",
    "struct_bullets",
    // Code block protection
    "code_fenced",
    "code_inline",
    // Escape handling
    "escape_sigma",
    "escape_arrow",
    // Logic density
    "logic_high",
    "logic_low",
    // Edge cases
    "edge_empty",
    "edge_whitespace",
    "edge_short",
    "edge_punctuation",
    "edge_unicode",
    "edge_mixed",
];

#[test]
fn golden_parity_spell_independent() {
    let fixtures = load_fixtures();

    for fixture in &fixtures {
        if !SPELL_INDEPENDENT_FIXTURES.contains(&fixture.name.as_str()) {
            continue;
        }
        let result = alientalk_daemon::engine::compile(&fixture.input);
        assert_eq!(
            result, fixture.expected,
            "\n--- GOLDEN PARITY FAILURE: {} ---\nInput:    {:?}\nExpected: {:?}\nGot:      {:?}\n",
            fixture.name, fixture.input, fixture.expected, result
        );
    }
}

/// Run all fixtures but only report mismatches (non-fatal).
/// This catches regressions without blocking CI until spell correction ships.
#[test]
fn golden_parity_all_report() {
    let fixtures = load_fixtures();
    let mut mismatches = Vec::new();

    for fixture in &fixtures {
        let result = alientalk_daemon::engine::compile(&fixture.input);
        if result != fixture.expected {
            mismatches.push(format!(
                "  {} — expected {:?}, got {:?}",
                fixture.name, fixture.expected, result
            ));
        }
    }

    if !mismatches.is_empty() {
        eprintln!(
            "\n=== Golden parity: {}/{} mismatches (spell-dependent may be expected) ===\n{}",
            mismatches.len(),
            fixtures.len(),
            mismatches.join("\n")
        );
    }
}
